# Generated by Django 3.0.5 on 2020-05-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'blog'},
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='blogImages/'),
        ),
    ]
