# Generated by Django 3.0.5 on 2020-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200519_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='categories',
            field=models.ManyToManyField(to='blog.Categories'),
        ),
    ]
