# Generated by Django 3.0.5 on 2020-05-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200524_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='categories',
            field=models.ManyToManyField(related_name='blogs', to='blog.Categories'),
        ),
    ]
