# Generated by Django 3.0.5 on 2020-04-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20200425_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='image',
            field=models.ImageField(upload_to='proj_images'),
        ),
    ]
