# Generated by Django 3.0.5 on 2020-04-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20200425_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
